### ISSUE TITLE
Unable to save configuration

### ISSUE THREAD

**Issue by baniol** [devopsfaith/krakendesigner#1]
Saving configuration on the http://designer.krakend.io/ page renders the error: "ReferenceError: saveAs is not defined". 
Also, FileSaver.js returns 404

**Comment by alombarte** [comment]
Thanks @baniol 
When I moved the designer to its own repository I deleted all JS from the www.krakend.io website. But the designer still uses to JS files that are not inside webpack.

The issue has been fixed but I will need to bring those files to the designer repo.

Thanks for reporting
