### ISSUE TITLE
Invalid character 'ï' looking for beginning of value

### ISSUE THREAD

**Issue by alombarte** [devopsfaith/krakendesigner#13]
Some generated files raise this error when starting krakend:
```
ERROR parsing the configuration file: Fatal error config file: While parsing config: invalid character 'ï' looking for beginning of value
```
It's not related to the content of the file but the Byte Order Mark (BOM) introduced to identify the file as UTF-8.

Temporary fix is to copy/paste the content in a new file, this usually fixes the problem as major editors don't introduce BOM. Or if your editor supports it, save the same file without BOM

**Comment by alombarte** [comment]
Fixed in production (Make sure to refresh browser cache)

**Comment by jackz7** [comment]
If someone is facing the same issue on windows, 

```
1. Create new file in notepad++ using ctrl+n
2. Save file as krakend.json and use it. (Don't open it in vs code until extreme necessary)
```

**Comment by CLONER-hub** [comment]
Hello friends, can anyone help me, I am having an error with the Singbox program in every configuration file
decode config: invalid character 'l' looking
for beginning of value: row 1, column 1


 It says: "Sing-box 1.9..0 rc 16
