### ISSUE TITLE
npm ERR! 404 Not Found: flatmap-stream@0.1.0

### ISSUE THREAD

**Issue by Ares2013** [devopsfaith/krakendesigner#41]
I am getting the following error while doing npm install.
npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.0

npm version: 6.5.0

Do you have a good solution?

**Comment by alombarte** [comment]
Hello @Ares2013 ,

All the code in the master branch is automatically built and uploaded to https://designer.krakend.io using the latest node version. You can check the .travis.yml file in the repository.

I have also tested locally using node 6.4.1 and it worked.
I deployed heavy changes yesterday concerning library updates, so you might be using a previous version and the pull is not working anymore for you.

I would suggest cloning the project in a fresh folder and do the `npm install` so there is no previous `node_modules` folder. Let me know if that worked for you, but as you can see code is live and passing the automatic build.

let me know if that worked

**Comment by alombarte** [comment]
I am closing the issue. Feel free to add any additional comments if you need further help.
