### ISSUE TITLE
Load a previous configuration file not working in Firefox

### ISSUE THREAD

**Issue by dragon28** [devopsfaith/krakendesigner#43]
Hello People,

Please kindly take a look at the "load a previous configuration file" at the dashboard section which are not working when I try to drag "krakend.json" from the desktop and drop it inside the "drop configuration file to load it".

I have test it on Linux Ubuntu 18.04 64 bits and Mac OS X on firefox web browser. Both version of firefox not working.

Thanks

**Comment by alombarte** [comment]
Thanks for reporting @dragon28,

Yes, you are right. It seems that Firefox is not working. We will investigate why is that. In the meantime, Safari and Chrome are working fine if you need to use the tool.

Thanks

**Comment by alombarte** [comment]
Hello @dragon28 , that should be fixed now
