### ISSUE TITLE
Numbers wrapped in quotes when saved

### ISSUE THREAD

**Issue by s4nji** [devopsfaith/krakendesigner#46]
#### Steps to reproduce
1. Create or load a configuration.
2. Go to Metrics and Logging section, tick OpenCensus and Prometheus.
3. Write `9091` in the port number field.
4. Save the configuration.

#### Issue
* The port number in the configuration file is wrapped with quotes.  
* When verified with `krakend -c config.json check`, it returns `Syntax OK`
* When actually used to start krakend, the following error occurs:
```
 WARNING: opencensus: json: cannot unmarshal string into Go struct field .port of type int
```

**Comment by alombarte** [comment]
Thanks for reporting @s4nji 

Now it's fixed.

**Comment by s4nji** [comment]
Hey @alombarte! FYI, the same issue seems to also happen with sampling rate and reporting period/interval, but only if you interact with the input field.

**Comment by alombarte** [comment]
@s4nji It looks like I had a good day :D

Please let me know if you find anything else. We usually set these values by hand, so it's easy to miss. Thanks!
