### ISSUE TITLE
It is allowed to generate an invalid configuration file (static response with no backends)

### ISSUE THREAD

**Issue by PuKoren** [devopsfaith/krakendesigner#58]
Right now, it is possible to create a new route without any backend, and export the configuration file without any warning or error, while the configuration file is rejected by KrakenD because it contains no backends

Reproduction steps:
  - Create a service
  - Create a new route
  - Export the configuration file

My use case was that I was trying to create a fixture route, returning always static data. I exported the configuration that was rejected and I had to add some fake backends to the configuration to make it work

**Comment by alombarte** [comment]
The button is disabled now until no backends are added. I have also corrected the JSON checker for the provided object.

It will be available online as soon as I merge the `0.9` branch. I will also tag the docker image as `0.9`.

**Comment by alombarte** [comment]
- Docker image tagged as 0.9
- Fix is live!
