### ISSUE TITLE
Datadog support

### ISSUE THREAD

**Issue by alombarte** [devopsfaith/krakendesigner#72]
Add `datadog` under `exporters`
```
type DataDogConfig struct {
	Namespace              string                 `json:"namespace"`
	Service                string                 `json:"service"`
	TraceAddr              string                 `json:"trace_address"`
	StatsAddr              string                 `json:"stats_address"`
	Tags                   []string               `json:"tags"`
	GlobalTags             map[string]interface{} `json:"global_tags"`
	DisableCountPerBuckets bool                   `json:"disable_count_per_buckets"`
}
```
Keep sample rate: 100 (agent does the samping)

**Comment by kpacha** [comment]
related to https://github.com/devopsfaith/krakend-opencensus/pull/37

**Comment by garry-jeromson** [comment]
Any ETA on Designer support for the Datadog config? It'd be super useful, since there's no examples or documentation for it yet. (Looking at the `DataDogConfig` struct and guessing what the config should look like is an option, but it's not clear if there are any gotchas to be aware of.)

**Comment by alombarte** [comment]
Hi @garry-jeromson , KrakenD 1.2 with Datadog support was released yesterday, and also the docs that you can find here:
https://www.krakend.io/docs/logging-metrics-tracing/datadog/

The designer will add it VERY soon

**Comment by alombarte** [comment]
Published

**Comment by garry-jeromson** [comment]
That was indeed _very_ soon. Thanks!
