### ISSUE TITLE
Connected JWT-Validation configuration between endpoints

### ISSUE THREAD

**Issue by Alphyron** [devopsfaith/krakendesigner#82]
Hello,

there is a bug with connected jwt validation configuration.
If you create multiple endpoints and enable the jwt validation you cannot change one without the other.
So if you want to change the roles or any other configuration on endpoint-1 it will have the same effect with endpoint-2.
But this bug only appears if you create new endpoints. If you load an existing file you can change the endpoints without changing the other ones.

**Comment by alombarte** [comment]
Thanks for reporting!

Should be fixed now. Values were passed by reference when creating new objects.
