### ISSUE TITLE
Loading pre-saved krakend.json files

### ISSUE THREAD

**Issue by ChristofBlanc** [devopsfaith/krakendesigner#87]
Firstly, great job with the development of Krakend designed.

Secondly, apologies - this is more of a feature suggestion than an "issue", per se.

So, was wondering if there are any plans to reload a krakend.json file that's been created in the designer back into the designer so you can start editing again? Currently all edits are lost when you close the page so you have to start again from scratch.

**Comment by alombarte** [comment]
Hello @ChristofBlanc ,

This feature is implemented from day one, wondering why you can't see it. When you open the KrakenDesigner, on its front page (the Dashboard), you should see a gray square with a bigger text saying "Drop configuration file to load it.". Just drag the krakend.json file in there and you'll continue where you left it. If you have problems using this, please reopen and show me some screenshots.

**Comment by ChristofBlanc** [comment]
You are right - apologies! 🤭

I had been using the "save" icon on the left hand panel to save my config file rather than the "Download this configuration" button on the landing page hence was probably expecting to see a "load" icon near it.

Anyhoo, glad the feature is there. Thanks.
