### ISSUE TITLE
Timeouts and TTL on Service configuration: always default values

### ISSUE THREAD

**Issue by mdonat** [devopsfaith/krakendesigner#97]
When loading a configuration with Timeout and TTL values on service configuration these values are ignored. 
It seems even going to another section and back to service configuration resets this values.
Also "Available hosts" are not loaded correctly from config-files, it seems previously entered hosts are not removed when loading a config-file.

**Comment by alombarte** [comment]
Thanks @mdonat for reporting. All issues described have been solved.
